# Generated by Django 5.2.4 on 2025-07-29 21:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Portfolio name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Portfolio description')),
                ('is_default', models.BooleanField(default=False, help_text='Default portfolio for user')),
            ],
            options={
                'db_table': 'mapletrade_portfolios',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Sector name (e.g., Technology)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Sector code (e.g., TECH)', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Sector description')),
                ('etf_symbol', models.CharField(help_text='Representative ETF symbol (e.g., XLK)', max_length=10)),
                ('volatility_threshold', models.DecimalField(decimal_places=4, default=0.42, help_text='Volatility threshold for this sector', max_digits=5)),
            ],
            options={
                'db_table': 'mapletrade_sectors',
                'indexes': [models.Index(fields=['name'], name='mapletrade__name_43fb84_idx'), models.Index(fields=['code'], name='mapletrade__code_67d025_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(help_text='Stock ticker symbol', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Company name', max_length=200)),
                ('exchange', models.CharField(blank=True, help_text='Stock exchange', max_length=50)),
                ('currency', models.CharField(default='USD', help_text='Trading currency', max_length=3)),
                ('market_cap', models.BigIntegerField(blank=True, help_text='Market capitalization', null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, help_text='Current/last traded price', max_digits=12, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, help_text='Analyst target price', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether stock is actively tracked')),
                ('last_updated', models.DateTimeField(blank=True, help_text='Last data update', null=True)),
                ('sector', models.ForeignKey(blank=True, help_text="Stock's sector classification", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sector')),
            ],
            options={
                'db_table': 'mapletrade_stocks',
            },
        ),
        migrations.CreateModel(
            name='PortfolioStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='User notes about this stock')),
                ('shares', models.DecimalField(blank=True, decimal_places=4, help_text='Number of shares owned', max_digits=12, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=4, help_text='Average purchase price', max_digits=12, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
            options={
                'db_table': 'mapletrade_portfolio_stocks',
            },
        ),
    ]
