# Generated by Django 5.2.4 on 2025-07-29 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.userportfolio'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol'], name='mapletrade__symbol_790a38_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sector'], name='mapletrade__sector__708c03_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['is_active'], name='mapletrade__is_acti_1ade0f_idx'),
        ),
        migrations.AddIndex(
            model_name='userportfolio',
            index=models.Index(fields=['user'], name='mapletrade__user_id_7c2445_idx'),
        ),
        migrations.AddIndex(
            model_name='userportfolio',
            index=models.Index(fields=['is_default'], name='mapletrade__is_defa_496818_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userportfolio',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='portfoliostock',
            index=models.Index(fields=['portfolio'], name='mapletrade__portfol_9e2696_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliostock',
            index=models.Index(fields=['added_date'], name='mapletrade__added_d_dcfe69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliostock',
            unique_together={('portfolio', 'stock')},
        ),
    ]
