# Generated by Django 4.2.7 on 2025-07-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_analytics_engine_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricedata',
            name='unique_stock_price_date',
        ),
        migrations.RemoveIndex(
            model_name='portfoliostock',
            name='mapletrade__added_d_dcfe69_idx',
        ),
        migrations.RenameIndex(
            model_name='analysisresult',
            new_name='mapletrade__stock_i_ce3ba2_idx',
            old_name='mapletrade_analysis_stock_date_idx',
        ),
        migrations.RenameIndex(
            model_name='analysisresult',
            new_name='mapletrade__analysi_95d584_idx',
            old_name='mapletrade_analysis_date_idx',
        ),
        migrations.RenameIndex(
            model_name='analysisresult',
            new_name='mapletrade__signal_5db7f8_idx',
            old_name='mapletrade_analysis_signal_idx',
        ),
        migrations.RenameIndex(
            model_name='analysisresult',
            new_name='mapletrade__stock_i_a784bb_idx',
            old_name='mapletrade_analysis_stock_signal_idx',
        ),
        migrations.RenameIndex(
            model_name='pricedata',
            new_name='mapletrade__stock_i_234597_idx',
            old_name='mapletrade_price_stock_date_idx',
        ),
        migrations.RenameIndex(
            model_name='pricedata',
            new_name='mapletrade__date_2339d9_idx',
            old_name='mapletrade_price_date_idx',
        ),
        migrations.AlterUniqueTogether(
            name='pricedata',
            unique_together={('stock', 'date')},
        ),
        migrations.AddIndex(
            model_name='portfoliostock',
            index=models.Index(fields=['stock'], name='mapletrade__stock_i_33a959_idx'),
        ),
    ]
