# Generated by Django 4.2.7 on 2025-07-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_pricedata_unique_stock_price_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricedata',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='portfoliostock',
            name='mapletrade__portfol_9e2696_idx',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='engine_version',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='outperformance',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='sector_etf',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='sector_name',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='sector_volatility_threshold',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='target_above_price',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='target_price',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='volatility_below_threshold',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='errors',
            field=models.JSONField(blank=True, default=list, help_text='Any errors during analysis'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Whether this analysis is still valid'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='low_volatility',
            field=models.BooleanField(default=False, help_text='Volatility below threshold'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Complete analysis data'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='target_above_current',
            field=models.BooleanField(default=False, help_text='Target price above current'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='analysis_period_months',
            field=models.IntegerField(default=6, help_text='Analysis period in months'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='confidence',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Confidence score (0-1)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='outperformed_sector',
            field=models.BooleanField(default=False, help_text='Stock outperformed sector ETF'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='rationale',
            field=models.TextField(blank=True, help_text='Explanation for the recommendation'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='sector_return',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Sector ETF return percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='signal',
            field=models.CharField(choices=[('BUY', 'Buy'), ('HOLD', 'Hold'), ('SELL', 'Sell')], help_text='Investment recommendation', max_length=4),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='stock_return',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Stock return percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='volatility',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Annualized volatility percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='adjusted_close',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Adjusted closing price', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='date',
            field=models.DateField(help_text='Price date'),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='high_price',
            field=models.DecimalField(decimal_places=4, help_text='High price', max_digits=12),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='low_price',
            field=models.DecimalField(decimal_places=4, help_text='Low price', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='portfoliostock',
            index=models.Index(fields=['added_date'], name='mapletrade__added_d_dcfe69_idx'),
        ),
    ]
