# Generated by Django 4.2.7

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pricedata_options_and_more'),
    ]

    operations = [
        # Add new fields to AnalysisResult if they don't exist
        migrations.AddField(
            model_name='analysisresult',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Stock price at analysis time', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='engine_version',
            field=models.CharField(default='1.0.0', help_text='Analytics engine version', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='outperformance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Stock outperformance vs sector', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='sector_etf',
            field=models.CharField(blank=True, help_text='Sector ETF used for comparison', max_length=10),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='sector_name',
            field=models.CharField(blank=True, help_text='Sector name at time of analysis', max_length=100),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='sector_volatility_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Sector volatility threshold at time of analysis', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='target_above_price',
            field=models.BooleanField(default=False, help_text='Target price above current'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Analyst target price at analysis time', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='volatility_below_threshold',
            field=models.BooleanField(default=False, help_text='Volatility below sector threshold'),
        ),
        
        # Add indexes for new fields
        migrations.AddIndex(
            model_name='pricedata',
            index=models.Index(fields=['stock', '-date'], name='core_priced_stock_i_5f8a12_idx'),
        ),
    ]