# Generated by Django 4.2.7 on 2025-08-02 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='user',
            field=models.ForeignKey(help_text='User who requested this analysis', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectoranalysis',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_analyses', to='data.sector'),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='analysis_result',
            field=models.ForeignKey(help_text='Analysis that triggered this change', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_changes', to='analytics.analysisresult'),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to='data.stock'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='data.stock'),
        ),
        migrations.AddIndex(
            model_name='technicalindicator',
            index=models.Index(fields=['stock', '-date'], name='mapletrade__stock_i_dc8e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalindicator',
            index=models.Index(fields=['date'], name='mapletrade__date_ad3b98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technicalindicator',
            unique_together={('stock', 'date')},
        ),
        migrations.AddIndex(
            model_name='stockanalysis',
            index=models.Index(fields=['user', '-created_at'], name='mapletrade__user_id_10d3fb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockanalysis',
            index=models.Index(fields=['stock', '-created_at'], name='mapletrade__stock_i_be95db_idx'),
        ),
        migrations.AddIndex(
            model_name='stockanalysis',
            index=models.Index(fields=['signal', '-created_at'], name='mapletrade__signal_45ee91_idx'),
        ),
        migrations.AddIndex(
            model_name='stockanalysis',
            index=models.Index(fields=['created_at'], name='mapletrade__created_9de244_idx'),
        ),
        migrations.AddIndex(
            model_name='stockanalysis',
            index=models.Index(fields=['analysis_end_date'], name='mapletrade__analysi_2cd9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='sectoranalysis',
            index=models.Index(fields=['sector', '-analysis_date'], name='mapletrade__sector__7499bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sectoranalysis',
            unique_together={('sector', 'analysis_date')},
        ),
        migrations.AddIndex(
            model_name='recommendationhistory',
            index=models.Index(fields=['stock', '-created_at'], name='mapletrade__stock_i_decd0e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationhistory',
            index=models.Index(fields=['new_signal', '-created_at'], name='mapletrade__new_sig_f35d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['stock', 'analysis_date'], name='mapletrade__stock_i_ce3ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['analysis_date'], name='mapletrade__analysi_95d584_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['signal'], name='mapletrade__signal_5db7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['stock', 'signal'], name='mapletrade__stock_i_a784bb_idx'),
        ),
    ]
