# Generated by Django 4.2.7 on 2025-08-02 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Price date')),
                ('open_price', models.DecimalField(decimal_places=4, help_text='Opening price', max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=4, help_text='High price', max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=4, help_text='Low price', max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=4, help_text='Closing price', max_digits=12)),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=4, help_text='Adjusted closing price', max_digits=12, null=True)),
                ('volume', models.BigIntegerField(help_text='Trading volume')),
            ],
            options={
                'db_table': 'mapletrade_price_data',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Sector name (e.g., Technology)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Sector code (e.g., TECH)', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Sector description')),
                ('etf_symbol', models.CharField(help_text='Representative ETF symbol (e.g., XLK)', max_length=10)),
                ('volatility_threshold', models.DecimalField(decimal_places=4, default=0.42, help_text='Volatility threshold for this sector', max_digits=5)),
            ],
            options={
                'db_table': 'mapletrade_sectors',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(help_text='Stock ticker symbol', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Company name', max_length=200)),
                ('exchange', models.CharField(blank=True, help_text='Stock exchange', max_length=50)),
                ('currency', models.CharField(default='USD', help_text='Trading currency', max_length=3)),
                ('market_cap', models.BigIntegerField(blank=True, help_text='Market capitalization', null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, help_text='Current/last traded price', max_digits=12, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, help_text='Analyst target price', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether stock is actively tracked')),
                ('last_updated', models.DateTimeField(blank=True, help_text='Last data update', null=True)),
                ('sector', models.ForeignKey(blank=True, help_text="Stock's sector classification", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='data.sector')),
            ],
            options={
                'db_table': 'mapletrade_stocks',
            },
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['name'], name='mapletrade__name_43fb84_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['code'], name='mapletrade__code_67d025_idx'),
        ),
        migrations.AddField(
            model_name='pricedata',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='data.stock'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol'], name='mapletrade__symbol_790a38_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sector'], name='mapletrade__sector__708c03_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['is_active'], name='mapletrade__is_acti_1ade0f_idx'),
        ),
        migrations.AddIndex(
            model_name='pricedata',
            index=models.Index(fields=['stock', 'date'], name='mapletrade__stock_i_234597_idx'),
        ),
        migrations.AddIndex(
            model_name='pricedata',
            index=models.Index(fields=['date'], name='mapletrade__date_2339d9_idx'),
        ),
        migrations.AddIndex(
            model_name='pricedata',
            index=models.Index(fields=['stock', '-date'], name='mapletrade__stock_i_d941fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricedata',
            unique_together={('stock', 'date')},
        ),
    ]
