# Development-specific Docker Compose configuration
# Use this for development with only essential services
version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: mapletrade-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes --save 60 1000
    networks:
      - mapletrade-dev

volumes:
  redis_dev_data:
    driver: local

networks:
  mapletrade-dev:
    driver: bridge